freebsd_task:
  freebsd_instance:
    image_family: freebsd-12-2
  env:
    CIRRUS_CLONE_SUBMODULES: true
  deps_script:
    - sed -i.bak -e 's,/quarterly,/latest,' /etc/pkg/FreeBSD.conf
    - pkg install -y samurai
  matrix:
    - name: freebsd_clang
    - name: freebsd_gcc
      gcc_script: pkg install -y gcc
      env:
        CC: gcc
  test_script:
    - ./configure
    - samu -C_build test

linux_task:
  container:
    image: gcc:latest
  env:
    CIRRUS_CLONE_SUBMODULES: true
  deps_script:
    - apt-get update && apt-get -y install bash ninja-build
  matrix:
    - name: linux_clang
      env:
        CC: clang
      clang_script:
        - apt-get -y install clang llvm
    - name: linux_gcc
  test_script:
    - ./configure
    - SH=bash ninja -C_build test # bash for -o pipefail

macos_task:
  osx_instance:
    image: catalina-base
  env:
    CIRRUS_CLONE_SUBMODULES: true
  matrix:
    - name: macos_clang
      env:
        CC: clang
    - name: macos_gcc
      env:
        CC: gcc
  deps_script:
    - brew install samurai coreutils
  test_script:
    - ./configure
    - samu -C_build test
