freebsd_task:
  freebsd_instance:
    image_family: freebsd-12-2
  env:
    CIRRUS_CLONE_SUBMODULES: true
  deps_script:
    - sed -i.bak -e 's,/quarterly,/latest,' /etc/pkg/FreeBSD.conf
    - pkg install -y samurai
  matrix:
    - name: freebsd_clang
      test_script:
        - ./configure CC=cc
        - samu -C_build test
    - name: freebsd_gcc
      gcc_script: pkg install -y gcc11
      test_script:
        - ./configure CC=gcc11
        - samu -C_build test

linux_task:
  container:
    image: gcc:latest
  env:
    CIRRUS_CLONE_SUBMODULES: true
  deps_script:
    - apt-get update && apt-get -y install bash ninja-build
  matrix:
    - name: linux_clang
      clang_script:
        - apt-get -y install clang llvm
      test_script:
        - ./configure CC=clang
        - SH=bash ninja -C_build test # bash for -o pipefail
    - name: linux_gcc
      test_script:
        - ./configure CC=gcc
        - SH=bash ninja -C_build test # bash for -o pipefail

macos_task:
  osx_instance:
    image: monterey-base
  env:
    CIRRUS_CLONE_SUBMODULES: true
  deps_script:
    - brew install samurai coreutils
  matrix:
    - name: macos_clang
      test_script:
        - ./configure CC=clang
        - samu -C_build test
    - name: macos_gcc
      test_script:
        - ./configure CC=gcc
        - samu -C_build test
