/*-
 * SPDX-License-Identifier: BSD-2-Clause-FreeBSD
 *
 * Copyright (c) 2019 Tobias Kortkamp <tobik@FreeBSD.org>
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
 * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 */

#include "config.h"

#include "enum.h"

const char *ParserASTBuilderTokenType_tostring[] = {
	[PARSER_AST_BUILDER_TOKEN_COMMENT] = "PARSER_AST_BUILDER_TOKEN_COMMENT",
	[PARSER_AST_BUILDER_TOKEN_CONDITIONAL_END] = "PARSER_AST_BUILDER_TOKEN_CONDITIONAL_END",
	[PARSER_AST_BUILDER_TOKEN_CONDITIONAL_TOKEN] = "PARSER_AST_BUILDER_TOKEN_CONDITIONAL_TOKEN",
	[PARSER_AST_BUILDER_TOKEN_CONDITIONAL_START] = "PARSER_AST_BUILDER_TOKEN_CONDITIONAL_START",
	[PARSER_AST_BUILDER_TOKEN_TARGET_COMMAND_END] = "PARSER_AST_BUILDER_TOKEN_TARGET_COMMAND_END",
	[PARSER_AST_BUILDER_TOKEN_TARGET_COMMAND_START] = "PARSER_AST_BUILDER_TOKEN_TARGET_COMMAND_START",
	[PARSER_AST_BUILDER_TOKEN_TARGET_COMMAND_TOKEN] = "PARSER_AST_BUILDER_TOKEN_TARGET_COMMAND_TOKEN",
	[PARSER_AST_BUILDER_TOKEN_TARGET_END] = "PARSER_AST_BUILDER_TOKEN_TARGET_END",
	[PARSER_AST_BUILDER_TOKEN_TARGET_START] = "PARSER_AST_BUILDER_TOKEN_TARGET_START",
	[PARSER_AST_BUILDER_TOKEN_VARIABLE_END] = "PARSER_AST_BUILDER_TOKEN_VARIABLE_END",
	[PARSER_AST_BUILDER_TOKEN_VARIABLE_START] = "PARSER_AST_BUILDER_TOKEN_VARIABLE_START",
	[PARSER_AST_BUILDER_TOKEN_VARIABLE_TOKEN] = "PARSER_AST_BUILDER_TOKEN_VARIABLE_TOKEN",
};

const char *ParserASTBuilderTokenType_humanize[] = {
	[PARSER_AST_BUILDER_TOKEN_COMMENT] = "comment",
	[PARSER_AST_BUILDER_TOKEN_CONDITIONAL_END] = "conditional-end",
	[PARSER_AST_BUILDER_TOKEN_CONDITIONAL_TOKEN] = "conditional-token",
	[PARSER_AST_BUILDER_TOKEN_CONDITIONAL_START] = "conditional-start",
	[PARSER_AST_BUILDER_TOKEN_TARGET_COMMAND_END] = "target-command-end",
	[PARSER_AST_BUILDER_TOKEN_TARGET_COMMAND_START] = "target-command-start",
	[PARSER_AST_BUILDER_TOKEN_TARGET_COMMAND_TOKEN] = "target-command-token",
	[PARSER_AST_BUILDER_TOKEN_TARGET_END] = "target-end",
	[PARSER_AST_BUILDER_TOKEN_TARGET_START] = "target-start",
	[PARSER_AST_BUILDER_TOKEN_VARIABLE_END] = "variable-end",
	[PARSER_AST_BUILDER_TOKEN_VARIABLE_START] = "variable-start",
	[PARSER_AST_BUILDER_TOKEN_VARIABLE_TOKEN] = "variable-token",
};

const char *ParserASTBuilderConditionalType_humanize[] = {
	[PARSER_AST_BUILDER_CONDITIONAL_INVALID] = "<invalid>",
	[PARSER_AST_BUILDER_CONDITIONAL_ELIF] = ".elif",
	[PARSER_AST_BUILDER_CONDITIONAL_ELIFDEF] = ".elifdef",
	[PARSER_AST_BUILDER_CONDITIONAL_ELIFMAKE] = ".elifmake",
	[PARSER_AST_BUILDER_CONDITIONAL_ELIFNDEF] = ".elifndef",
	[PARSER_AST_BUILDER_CONDITIONAL_ELSE] = ".else",
	[PARSER_AST_BUILDER_CONDITIONAL_ENDFOR] = ".endfor",
	[PARSER_AST_BUILDER_CONDITIONAL_ENDIF] = ".endif",
	[PARSER_AST_BUILDER_CONDITIONAL_ERROR] = ".error",
	[PARSER_AST_BUILDER_CONDITIONAL_EXPORT_ENV] = ".export-env",
	[PARSER_AST_BUILDER_CONDITIONAL_EXPORT_LITERAL] = ".export-literal",
	[PARSER_AST_BUILDER_CONDITIONAL_EXPORT] = ".export",
	[PARSER_AST_BUILDER_CONDITIONAL_FOR] = ".for",
	[PARSER_AST_BUILDER_CONDITIONAL_IF] = ".if",
	[PARSER_AST_BUILDER_CONDITIONAL_IFDEF] = ".ifdef",
	[PARSER_AST_BUILDER_CONDITIONAL_IFMAKE] = ".ifmake",
	[PARSER_AST_BUILDER_CONDITIONAL_IFNDEF] = ".ifndef",
	[PARSER_AST_BUILDER_CONDITIONAL_IFNMAKE] = ".ifnmake",
	[PARSER_AST_BUILDER_CONDITIONAL_INCLUDE] = ".include",
	[PARSER_AST_BUILDER_CONDITIONAL_INCLUDE_OPTIONAL] = ".-include",
	[PARSER_AST_BUILDER_CONDITIONAL_INCLUDE_OPTIONAL_D] = ".dinclude",
	[PARSER_AST_BUILDER_CONDITIONAL_INCLUDE_OPTIONAL_S] = ".sinclude",
	[PARSER_AST_BUILDER_CONDITIONAL_INCLUDE_POSIX] = "include",
	[PARSER_AST_BUILDER_CONDITIONAL_INCLUDE_POSIX_OPTIONAL] = "-include",
	[PARSER_AST_BUILDER_CONDITIONAL_INCLUDE_POSIX_OPTIONAL_S] = "sinclude",
	[PARSER_AST_BUILDER_CONDITIONAL_INFO] = ".info",
	[PARSER_AST_BUILDER_CONDITIONAL_UNDEF] = ".undef",
	[PARSER_AST_BUILDER_CONDITIONAL_UNEXPORT_ENV] = ".unexport-env",
	[PARSER_AST_BUILDER_CONDITIONAL_UNEXPORT] = ".unexport",
	[PARSER_AST_BUILDER_CONDITIONAL_WARNING] = ".warning",
};
